### ISSUE TITLE
'바닥부터 배우는 강화학습' 책 오타 문의

### ISSUE THREAD

**Issue by namdori61** [seungeunrho/RLfrombasics#2]
안녕하세요, 노승은님.
저는 '바닥부터 배우는 강화학습' 책으로 강화학습을 처음 공부하고있는 남상호 라고 합니다.
먼저, 좋은 책 써주셔서 강화학습 쉽게 잘 공부하고 있습니다 감사합니다:)

다름이 아니고, 책 내용 관련해서 수정 필요한 부분이 있는 것 같아서 문의 드립니다.
(깃헙 채널로 문의드리는게 맞는지 모르겠으나, 이게 빠를 것 같아서 이쪽으로 문의드립니다.)

문의 내용은 아래 2개 이슈 입니다.

1. 67페이지 OX퀴즈 내용 및 69 페이지 정답 관련 수식 (형광펜으로 표시)
원래 책 내용은 아래와 같이 되어 있는데요, 2번에서 기대값 함수 내의 2번째 항은 t+2 로 수정이 되어야 맞지 않나요?
![KakaoTalk_Photo_2020-11-30-10-21-05](https://user-images.githubusercontent.com/20228736/100559509-496a9f00-32f6-11eb-8d2d-b19930319df6.jpeg)

수정하면 아래와 같이 되는게 맞는거 같습니다. (두 스텝 째의 틱은 t+2가 맞으므로)
![KakaoTalk_Photo_2020-11-30-10-20-56](https://user-images.githubusercontent.com/20228736/100559569-79b23d80-32f6-11eb-820e-89a6f5da5bb3.jpeg)

2. 141페이지 QAgent 클래스 코드
간단한 오탈자 인데, init 함수 내에서 self.alpha 정의 시에 s가 빠진 것 같습니다. (깃헙 코드는 정상적입니다)
![KakaoTalk_Photo_2020-11-30-10-20-46](https://user-images.githubusercontent.com/20228736/100559619-a1090a80-32f6-11eb-8ce0-856ed7b79993.jpeg)

다시 한번 좋은 책 써주셔서 감사드립니다:)

**Comment by seungeunrho** [comment]
말씀주신 내용이 맞습니다.
중요한 부분에 오타가 있어 독자분들이 헷갈리실까 염려되는 마음이네요..
감사합니다!

노승은 드림
