### ISSUE TITLE
CH5_MCLearning.py line97

### ISSUE THREAD

**Issue by goodjian7** [seungeunrho/RLfrombasics#3]

**Comment by goodjian7** [comment]
덕분에 강화학습 잘 공부하고 있습니다.
공부하다가 ch5_mclearning.py 코드 97라인이 약간 이상해서 코멘트 남깁니다.

cum_reward = cum_reward + gamma * reward 로 되어 있는데, G_t에 gamma가 계속 곱해지는거면,
cum_reward = reward + gamma * cum_reward 로 바꿔야 되는거 아닌가 싶습니다.

어디에 물어봐야할지 모르겠어서 일단 깃허브에 남깁니다.
감사합니다.

**Comment by seungeunrho** [comment]
안녕하세요, 노승은입니다.
답변이 늦어 죄송합니다.
정확히 말씀 주셨습니다. 오타가 맞습니다.
수정하여 새로 푸시하였습니다.

감사합니다!!
